#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2017

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 --target=AppVeyor

#---------------------------------#
# Tests
#---------------------------------#
test: off

#---------------------------------#
#  Pull Requests                  #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#  General                        #
#---------------------------------#
skip_branch_with_pr: true

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - master
    - /support/.*/
    - /hotfix/.*/
    - /feature/.*/
    - /bugfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> build.cake, build.config

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /\(doc\).*/

